import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "BigBrain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white lg:bg-zinc-100 dark:bg-zinc-900 dark:lg:bg-zinc-950">
      <body className='antialiased'>
        {children}
      </body>
    </html>
  );
}
